version: '2'

services:
  
  #database service
  db:
    image: mongo:3.6
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb:/data/db
    command: --smallfiles
  
  #redis
  redis:
    image: "redis:alpine"

    command: redis-server

    ports:
      - "6379:6379"

    volumes:
      - ./data/redis:/var/lib/redis
      - ./data/redis/redis.conf:/usr/local/etc/redis/redis.conf
  
  # web service for flask application
  web:
    # container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    image: flask-scaffolding:assessment
    env_file:
      local.env
    command: >
      /bin/ash -c "
        flask run --host=0.0.0.0; 
      "
    volumes:
      - ./src/:/code
      - ./logs:/var/log/scaffolding
    ports:
      - "8400:5000"

    depends_on:
      - db
      - redis
  
  # celery worker
  worker:
    # container_name: worker
    build:
      context: .
    hostname: worker
    command: celery -A celery_app worker --loglevel=info
    env_file:
      local.env
    volumes:
      - ./src/:/code
    links:
      - redis
    depends_on:
      - redis
  
  # celery monitor
  monitor:
    # container_name: monitor
    build:
      context: .
    hostname: monitor
    ports:
      - "5555:5555"
    entrypoint: flower
    command:  -A celery_app --port=5555 --broker=redis://redis:6379/0
    env_file:
      local.env
    volumes:
      - ./src/:/code
    links:
      - redis
    depends_on:
      - redis
